### ISSUE TITLE
Not Working -- What Am I Missing?

### ISSUE THREAD

**Issue by MrPoetry** [ryanjamurphy/macOS-keyboard-nav-obsidian#8]
I just last night installed Obsidian for the first time on my iPad Pro (2018, iOS 14.latest), and it took me about 4 seconds to discover the opt+↑ / opt+↓ problem. I found and installed and enabled your plugin, but I can't get it to work. I'm using a Logitech K811 bluetooth keyboard. Obsidian insists, when I press either key combo (opt+↑ / opt+↓), on _moving_ the current paragraph! up/down a line. This, to me, is insane behavior. Perhaps it's Emacs? In case that was the problem, I disabled "Legacy Emacs-style keybindings" in Editor-preferences, but that had no effect. The only way I can get Obsidian to stop moving my paragraph when pressing opt+↑ / opt+↓ is to assign those hotkeys to some other function. But when I do that, I _still_ don't get the desired effects of your plugin.

What am I missing?

P.S. Today I installed Obsidian on my Macbook Pro, and your plugin works perfectly on the MBP.

**Comment by ryanjamurphy** [comment]
Hmm. Maybe you have those hotkeys set in Preferences → Hotkeys? Search for "Swap lines" on your iPad.

(The label "Swap lines" will be switched to "Move lines" in an upcoming update, just in case you don't get to this right away. So, if you can't find "Swap lines," search for "Move lines" instead.)

**Comment by MrPoetry** [comment]
I did try changing those hotkeys:

- I tried deleting the hotkeys for Swap line up & Swap line down. No effect on problem.
- I tried assigning ctrl-alt-cmd-shift-up/down hotkeys (i.e. key combos I’ll never press) for Swap line up & Swap line down. No effect on problem.
- One aspect of your plugin works on my iPad: alt-shift-up/down arrow _does_ select from cursor position to top/bottom of paragraph. But alt-up/down still swaps paragraph up/down one line.

I'm beginning to wonder if this is a bug in Obsidian? I posted in the Help section of the Obsidian forum. Do you think I should file it as a bug?

**Comment by MrPoetry** [comment]
I did post the issue as a bug report in the Obsidian forum (https://forum.obsidian.md/t/can-t-unmap-alt-up-down-arrow-hotkeys-from-swapping-current-paragraph-up-down/32778) -- but this is the reply I got from the moderator:

[WhiteNoise](https://forum.obsidian.md/u/WhiteNoise) wrote:
"Sorry, I can’t reproduce your problem and we don’t provide support for third party plugins."

Have you or has anyone tested your plugin on the iPad and found that it works without the problem I describe above?

**Comment by ryanjamurphy** [comment]
I just realized that I'm not even using this plugin on iPad. Maybe that's the problem, hah. Disable the plugin and try the native experience? Maybe the hotkeys were assigned when you first installed Obsidian, then you installed the plugin, then you disabled the conflicting hotkeys, and now the plugin is causing problems. 

Edit: I didn't directly answer your question. No, I have no problems using alt+arrow keys on iPad.

**Comment by MrPoetry** [comment]
Problem solved: the rogue behavior was corrected in the Insider build 1.1.0, which I've installed. So I am now happily able to use your plugin as you intended it. Thanks for your quick responses!
