### ISSUE TITLE
ArroyKey left and right

### ISSUE THREAD

**Issue by aseth0** [ryanjamurphy/macOS-keyboard-nav-obsidian#9]
Hi, 
could you consider create the shorcuts to select word by word using the `option+shift+ArrowKey[left|rigth]` to select the text word  every time you touch the arroy key?😅
greatings!

**Comment by violet-fish** [comment]
I fixed this issue on my install by resetting the navigate forward / back hotkeys to default. I'm guessing they got synced from windows when I turned on hotkey sync
